### ISSUE TITLE
Broken Build Badge in `README.md`

### ISSUE THREAD

**Issue by nelsonic** [grisp/grisp#123]
Greetings Fellow Grispers! 👋 
While reading the docs noticed that the build badge is broken: 💔 

![grisp-build-badge-broken](https://github.com/grisp/grisp/assets/194400/b08bbb19-d21e-4808-b338-2e24ada62574)

Currently the code is:
https://github.com/grisp/grisp/blob/7932167dd3fe3c08d1aaff3cb5c4501d7f51b6aa/README.md?plain=1#L8-L10

Replacing the `src` URL from:

```md
https://img.shields.io/github/workflow/status/grisp/grisp/Continuous%20Integration?style=flat-square
```
To:

```md
https://img.shields.io/github/actions/workflow/status/grisp/grisp/continous_integration.yaml?label=build&style=flat-square&branch=master
```

Will fix the badge:

[![continous integration](https://img.shields.io/github/actions/workflow/status/grisp/grisp/continous_integration.yaml?label=build&style=flat-square&branch=master)](https://github.com/grisp/grisp/actions/workflows/continous_integration.yaml)

**Comment by eproxus** [comment]
Fixed in #124
