### ISSUE TITLE
Document Pin mapping in wiki

### ISSUE THREAD

**Issue by nextl00p** [grisp/grisp#13]

**Comment by eproxus** [comment]
Which pins are we talking about here?

**Comment by eproxus** [comment]
@peerst Do you know where to find the above information?

**Comment by peerst** [comment]
Should make a more readable description but for now:

[PinoutV1.1.pdf](https://github.com/grisp/grisp/files/2171362/PinoutV1.1.pdf)

**Comment by eproxus** [comment]
Done. Documentation [here](https://hexdocs.pm/grisp/grisp_gpio.html).
