### ISSUE TITLE
grisp_led is accepting interval 0 (as well as negative intervals)

### ISSUE THREAD

**Issue by ThomasArts** [grisp/grisp#2]
Nobody in its right mind is ever to flash a led with interval 0 or -1, but there is a subtle difference between the two.

When using a negative interval, the grisp_led server will crash (due to a call to send_after with negative number). It will be restarted and the leds will all be black.

When using a zero interval, the led will constantly be switched on an off in the rate the hardware can handle. This may eventually fill the mail box.

**Comment by nextl00p** [comment]
What should be the intended behaviour? Turn it off?

At the moment the interval is given as-is to the timer which expects a value >= 0.

We cannot use throw, to indicate failure to the caller, as everything is happening in a async cast, so simply turning it off is the best idea in my opinion.

**Comment by eproxus** [comment]
I think it would be confusing to implement different behaviors just based on the integers. I'd prefer is function clause errors would be generated for anything below 1.

**Comment by ThomasArts** [comment]
Agreed, having a function clause error makes full sense.
