### ISSUE TITLE
[QUESTION] Patch file for OTP 22.3.1

### ISSUE THREAD

**Issue by Laymer** [grisp/grisp#75]
### Versions

* OS: macOS Catalina `10.15.4`
* GRiSP Toolchain: `3cb89929613a3a2c33ec81d0d29be2ec5a82eaaf`
* Erlang: `22.0`
* Rebar: rebar3 `v3.13.1`

### Description

Hello :)

Recently bumped into the same error message as reported by @eproxus here :

https://bugs.erlang.org/browse/ERL-1205

While building OTP 22.0 for GRiSP. 

And just noticed that there is a failing CI/CD build for PR #74 due to patchfile for OTP 22.3 missing. Since the OTP build error should be patched in OTP 22.3.1 and higher, I was wondering if there is actually something in progress towards OTP 22.3 for GRiSP ? I've seen that there is a branch on the [grisp/otp](https://github.com/grisp/otp) fork labelled 22.3, and a CI/CD pipeline for that version, has  so I assumed it was WIP. Is there something in preparation for OTP 22.3.1 as well? This version will normally have the merged PR for the OTP build error included, so I was wondering if it could be useful to have it available for GRiSP too? 🙂 

Thanks !

Best,
Igor

**Comment by sylane** [comment]
Is this still relevant ? We are supporting more recent version of OTP, so I would say no, but I prefer to check before closing...
